/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnergyCheckUtils */

#ifndef _Included_EnergyCheckUtils
#define _Included_EnergyCheckUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnergyCheckUtils
 * Method:    scale
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_EnergyCheckUtils_scale
  (JNIEnv *, jclass, jint);

/*
 * Class:     EnergyCheckUtils
 * Method:    freqAvailable
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_EnergyCheckUtils_freqAvailable
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    GetPackagePowerSpec
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_EnergyCheckUtils_GetPackagePowerSpec
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    GetDramPowerSpec
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_EnergyCheckUtils_GetDramPowerSpec
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    SetPackagePowerLimit
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_EnergyCheckUtils_SetPackagePowerLimit
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     EnergyCheckUtils
 * Method:    SetPackageTimeWindowLimit
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_EnergyCheckUtils_SetPackageTimeWindowLimit
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     EnergyCheckUtils
 * Method:    SetDramTimeWindowLimit
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_EnergyCheckUtils_SetDramTimeWindowLimit
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     EnergyCheckUtils
 * Method:    SetDramPowerLimit
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_EnergyCheckUtils_SetDramPowerLimit
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     EnergyCheckUtils
 * Method:    ProfileInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EnergyCheckUtils_ProfileInit
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    GetSocketNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EnergyCheckUtils_GetSocketNum
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    EnergyStatCheck
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnergyCheckUtils_EnergyStatCheck
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    ProfileDealloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EnergyCheckUtils_ProfileDealloc
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    SetPowerLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_EnergyCheckUtils_SetPowerLimit
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
