sed -i '/^Attempting/d' data_*.csv
sed -i '/^energy/d' data_*.csv
sed -i '/^reading/d' data_*.csv
sed -i '/^error/d' data_*.csv
sed -i '/^kmahmou1/d' data_*.csv
sed -i '/^Reading/d' data_*.csv
sed -i '/^Package/d' data_*.csv
sed -i '/^Pac/d' data_*.csv
sed -i '/^after/d' data_*.csv
sed -i '/^After/d' data_*.csv
